[package]
name = "springtime"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version = "1.62"
description = "Dependency injection based application bootstrapping and execution crate."
documentation = "https://docs.rs/springtime"
repository.workspace = true
license.workspace = true
keywords = ["di", "dependency-injection", "spring", "framework"]
readme = "README.md"

[features]
async = ["springtime-di/async", "threadsafe"]
default = ["async"]
threadsafe = ["springtime-di/threadsafe"]

[dependencies]
derive_more = "0.99.17"
springtime-di = { version = "0.3.0", path = "../springtime-di" }
thiserror = "1.0.39"

[dev-dependencies]
mockall = "0.11.4"
tokio = { version = "1.27.0", features = ["rt", "macros"] }
