[package]
name = "springtime-web-axum"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description = "Web framework based on Springtime and axum."
documentation = "https://docs.rs/springtime-web-axum"
repository.workspace = true
license.workspace = true
keywords = ["web", "http", "spring", "framework", "axum"]
readme = "README.md"

[features]
default = ["derive"]
derive = ["springtime-web-axum-derive"]

[dependencies]
axum = "0.6.15"
springtime = { version = "0.2.0", path = "../springtime" }
springtime-di = { version = "0.3.1", path = "../springtime-di" }
springtime-web-axum-derive = { version = "0.1.0", path = "../springtime-web-axum-derive", optional = true }

[dev-dependencies]
portpicker = "0.1.1"
tokio = { version = "1.27.0", features = ["rt", "macros", "rt-multi-thread"] }
