[package]
name = "springtime-web-axum"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description = "Web framework based on Springtime and Axum."
documentation = "https://docs.rs/springtime-web-axum"
repository.workspace = true
license.workspace = true
keywords = ["web", "http", "spring", "framework", "axum"]
readme = "README.md"

[dependencies]
axum = "0.6.15"
springtime = { version = "0.2.0", path = "../springtime" }
springtime-web-axum-derive = { version = "0.1.0", path = "../springtime-web-axum-derive" }
