[workspace]
members = ["springtime-di", "springtime-di-derive"]

[workspace.package]
authors = ["Kamil Rojewski <kamil.rojewski@gmail.com>"]
edition = "2021"
repository = "https://github.com/krojew/springtime"
readme = "./README.md"
license = "MIT"
