name: Continuous integration

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal toolchain with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      # run tests separately due to different default for the async feature
      - name: Run springtime-di tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets -p springtime-di
      - name: Run springtime tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets -p springtime
      - name: Format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy check
        run: cargo install cargo-hack && cargo hack --feature-powerset --exclude-features async,async-examples clippy --locked --release
      - name: Check async
        run: cargo run --example 09-async --features async-examples
